version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host 0.0.0.0'
        volumes:
            - .:/sklep_gry
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        image: mariadb
        environment: 
            MYSQL_DATABASE: sklep_gry
            MYSQL_USER: root
            MYSQL_ROOT: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - 8080:8080